# Installs modules to a new directory called 'modules'
moduledir './modules'

# Installs the acme/ohmyzsh module from the Puppet Forge
mod 'acme/ohmyzsh', '0.1.2'

# Installs the puppetlabs/vcsrepo module from its GitHub repository
mod 'vcsrepo',
  :git => 'https://github.com/puppetlabs/puppetlabs-vcsrepo'


# The following modules are used by the classroom setup and should be ignored.
moduledir './classroom'

mod 'arusso-stunnel'
#mod 'attachmentgenie-ssh'
mod 'badgerious-windowsenv'
mod 'binford2k-abalone'
mod 'chocolatey-chocolatey'
#mod 'croddy-make'
mod 'cyberious-pget'
#mod 'dwerder-grafana'
#mod 'dwerder-graphite'
mod 'garethr-docker'
#mod 'gentoo-portage'
#mod 'golja-gnupg'
#mod 'hunner-wordpress'
#mod 'jamtur01-irc'
mod 'jordan-fileshare'
mod 'maestrodev-rvm'
mod 'nanliu-staging'
mod 'pltraining-classroom'
mod 'pltraining-dirtree'
mod 'pltraining-dockeragent'
mod 'pltraining-puppetfactory'
mod 'pltraining-rbac'
mod 'pltraining-showoff'
mod 'pltraining-userprefs'
mod 'puppet-downloadfile'
mod 'puppet-iis'
mod 'puppet-windowsfeature'
mod 'puppetlabs-acl'
mod 'puppetlabs-apache'
mod 'puppetlabs-apt'
mod 'puppetlabs-concat'
mod 'puppetlabs-dsc'
mod 'puppetlabs-gcc'
mod 'puppetlabs-git'
#mod 'puppetlabs-haproxy'
mod 'puppetlabs-inifile'
mod 'puppetlabs-mysql'
mod 'puppetlabs-ntp'
mod 'puppetlabs-pegem'
mod 'puppetlabs-pepuppetservergem'
mod 'puppetlabs-powershell'
mod 'puppetlabs-puppetservergem'
mod 'puppetlabs-reboot'
mod 'puppetlabs-registry'
mod 'puppetlabs-ruby'
mod 'puppetlabs-stdlib'
mod 'puppetlabs-vcsrepo'
mod 'puppetlabs-windows'
mod 'puppetlabs-wsusclient'
mod 'stahnma-epel'
#mod 'zack-exports'
#mod 'zack-r10k'
